### ISSUE TITLE
Ephemeral disk encryption not working?

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry-incubator/bosh-aws-cpi-release#34]
I am not sure if I am doing something wrong but I can't get the ephemeral disk encryption to work.

Here is the section of the manifest:

```
resource_pools:
- cloud_properties:
    availability_zone: us-east-1b
    ephemeral_disk:
      cloud_properties:
        encrypted: true
        type: gp2
      size: 30000
    instance_type: t2.small
  name: small_z1
  network: cf1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3232.8
```

The `gp2` part and the size are picked up but not the encryption. We are using v53 for the CPI. Any ideas?

**Comment by cppforlife** [comment]
it should be:

```
resource_pools:
- cloud_properties:
    availability_zone: us-east-1b
    ephemeral_disk: # <--- no cloud props here
      encrypted: true
      type: gp2
      size: 30000
    instance_type: t2.small
  name: small_z1
  network: cf1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3232.8
```

**Comment by dlapiduz** [comment]
Thanks @cppforlife! Actually that is how we have it, the one I pasted is stuff I was trying out.

Here is the code we have in prod/staging: https://github.com/18F/cg-deploy-cf/blob/staging/cf-infrastructure-aws.yml#L73-L81.

Any other ideas of what it could be?

**Comment by cppforlife** [comment]
Hmm, nothing obvious. We'll try it out cc @ljfranklin.

**Comment by dlapiduz** [comment]
As a data point, encryption works fine for persistent disks when using disk pools.

**Comment by ljfranklin** [comment]
@dlapiduz Sorry you're seeing issues with this feature, unfortunately we're having trouble reproducing the failure. Your ephemeral disk config shown [here](https://github.com/18F/cg-deploy-cf/blob/2d62abf6f1c9b1e1955472f8a20778e1a4192947/cf-infrastructure-aws.yml#L97-L100) looks fine. We just ran a manual test with CPI v53 with an equivalent cloud-config and it worked as expected.

```
vm_types:
- name: encrypted
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk:
      size: 3000
      type: gp2
      encrypted: true
```

Our deployed VM shows two block devices, the root device `/dev/xvda` which is never encrypted (AWS limitation), and the ephemeral disk `/dev/sdb` which is an encrypted EBS volume of size 3GB. Just to confirm, you're seeing the same block devices, but the EBS volume shows "Not Encrypted"?
