### ISSUE TITLE
Support for Application Load Balancers

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry-incubator/bosh-aws-cpi-release#39]
Hi AWS CPI team,

can you please enable support for AWS ALBs? As of now, we can attach instances to ELBs like this:

```
resource_pools:
- name: ha_proxy_z1
  cloud_properties:
    elbs:
    - my-aws-elb
```

In a similar way we would like to attach instances to an [AWS ALB](https://aws.amazon.com/elasticloadbalancing/applicationloadbalancer/):

```
resource_pools:
- name: router_z1
  cloud_properties:
    elbs:
    - my-aws-alb
```

I think we can keep the property name "elbs" as the names for all load balancers is unique.

Thanks for your support and best regards,

  Jochen.
